# Site settings
title: ABC2019
email: abc@sozolab.jp
url: https://abc-research.github.io
description: "International Conference on Activity and Behavior Computing (ABC), which includes Human Activity Recognition with mobile / environmental sensors in ubiquitous / pervasive domains and with cameras in vision domains, and Human Behavior Analysis for long-term health care, rehabilitation, emotion recognition, human interaction, and so on."
keywords: "activity recognition, behavior analysis, international conference, activity and behavior computing"
conf_title1: "International Conference on"
conf_title2: "Activity and Behavior Computing"
meta_author: Sozo Inoue
location: Eastern Washington University, USA
date: Deadline extended to <b style="color:pink">Jan. 15, 2019!</b><br/>April 26-29, 2019
conjunction:
  name: ICIEV&IVPR2019
  url: http://cennser.org/ICIEV/

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

about:
  - text: "<b>Human Activity Recognition</b> has been researched in thousands of papers so far, with mobile / environmental sensors in ubiquitous / pervasive domains, and with cameras in vision domains. As well, <b>Human Behavior Analysis</b> is also explored for long-term health care, rehabilitation, emotion recognition, human interaction, and so on. However, many research challenges remain for realistic settings, such as complex and ambiguous activities / behavior, optimal sensor combinations, (deep) machine learning, data collection, platform systems, and killer applications."
  - text: "In this conference, we comprehend such research domains as <b>ABC</b>: <i>Activity and Behavior Computing</i>, and provide an open and a confluent place for discussing various aspects and the future of the ABC."

# Committee members
committee:
  - role: General Chairs
    member:
      - name: Sozo Inoue
        affil: Kyushu Institute of Technology / Riken, Japan
      - name: Atiqur Rahman Ahad
        affil: University of Dhaka, Bangladesh / Osaka University, Japan
  - role: Program Chairs
    member:
      - name: Ren Ohmura
        affil: Toyohashi University of Technology, Japan
      - name: Kazuya Murao
        affil: Ritsumeikan University, Japan
  - role: Publicity Chair
    member:
      - name: Paula Lago
        affil: Kyushu Institute of Technology, Japan
  - role: Publication Chair
    member:
      - name: Tsuyoshi Okita
        affil: Kyushu Institute of Technology, Japan
  - role: Advisory Board
    member:
      - name: Paul Lukowicz
        affil: DFKI, Germany
      - name: Kristof Van Laerhoven
        affil: University of Siegen, Germany
      - name: Daniel Roggen
        affil: University of Sussex, UK
      - name: Michael Beigl
        affil: Karlsruhe Institute of Technology, Germany
  - role: Secretaries
    member:
      - name: Tahera Hossain
        affil: Kyushu Institute of Technology, Japan
      - name: Moe Matsuki
        affil: Kyushu Institute of Technology, Japan
  - role: Program Committee (TBA)
    member:
      - name: Kristof Van Laerhoven
        affil: University of Siegen, Germany
      - name: Daniel Roggen
        affil: University of Sussex, UK
      - name: Susanna Pirttikangas
        affil: University of Oulu, Finland
      - name: Philipp M. Scholl
        affil: University of Freiburg, Germany
      - name: Hristijan Gjoreski
        affil: Ss. Cyril and Methodius University, Macedonia
      - name: Katsuhiko Kaji
        affil: Aichi Institute of Technology, Japan
      - name: Tsuyoshi Okita
        affil: Kyushu Institute of Technology / Riken, Japan
      - name: Paula Lago
        affil: Kyushu Institute of Technology, Japan
      - name: Kaori Fujinami
        affil: Tokyo University of Agriculture and Technology, Japan
      - name: Stephan Sigg
        affil: Aalto University, Finland
      - name: Hiroki Watanabe
        affil: Hokkaido University, Japan
      - name: Pascal Hirmer
        affil: University of Stuttgart, Germany
      - name: Shigeyuki Miyagi
        affil: The University of Shiga Prefecture, Japan
      - name: Yu Enokibori
        affil: Nagoya University, Japan
      - name: Anja Exler
        affil: Karlsruhe Institute of Technology, Germany
      - name: Kristina Yordanova
        affil: University of Rostock, Germany
      - name: Trung Thanh NGO
        affil: Osaka University, Japan
      - name: Ricky J Sethi
        affil: Fitchburg State University, USA
      - name: Meng Joo
        affil: Nanyang Technological University, Singapore
      - name: Ikuhisa Mitsugami
        affil: Hiroshima City University, Japan
      - name: Mohiuddin Ahmad	Khulna
        affil: University of Engineering & Technology, Bangladesh
      - name: Upal Mahbub
        affil: University of Meryland, College Park, USA



cfp:
  text:
    - text: "We welcome full technical papers, as well as concept papers related to ABC research. Technical papers describe the accuracy and performance of ABC Systems, real deployment cases or application of new paradigms such as deep learning to ABC. Concept papers describe the challenges and future directions of ABC based on  problems that arise when systems are deployed in real settings."
    - text: "The submitted papers are peer reviewed by experienced researchers, and accepted based on the research quality. To accept various research stages, an accepted paper can be either published in IEEE proceedings + USB, Open web + USB, or USB only upon authors' preference."
  scope:
    - item: Mobile sensor-based ABC
    - item: Environmental sensor-based ABC
    - item: Vision-based ABC
    - item: Multimodal ABC
    - item: Physical / semantic analysis of ABC
    - item: Gait analysis
    - item: Sleep analysis
    - item: Emotion recognition / analysis
    - item: ABC with deep learning
    - item: ABC data mining
    - item: Data collection
    - item: ABC systems
    - item: Interactive ABC
    - item: Healthcare applications
    - item: Sports applications
    - item: Business applications
    - item: Tools for industry
    - item: ABC in the wild
  format:
    - item: IEEE conference format (button below).
    - item: "4-6 pages: The authors can choose to give copyright to IEEE then the paper will be sent to IEEE Xplore as ICIEV-IVPR 2019 proceedings. "
    - item: "2-6 pages: The authors can choose not for IEEE and hence, copyright is not transfered."
    - item: Submit from Microsoft CMT for ICIEV2019  (button below) and select the ABC.
  dates:
    - name: Paper submission
      date: <strike>Dec. 17, 2018</strike> <b style="color:pink">&rarr;Jan. 15, 2019 (Anywhere on Earth)!</b>
    - name: Review result
      date: <strike>Jan. 31, 2019</strike> &rarr;Feb. 15, 2019
    - name: Camera ready
      date: <strike>Feb. 12, 2019</strike> &rarr;Feb. 28, 2019
    - name: Conference
      date: Apr. 26 - 29, 2019
  submit_url: https://cmt3.research.microsoft.com/User/Login?ReturnUrl=%2FICIEVIVPR2019
  template_url: https://www.ieee.org/conferences/publishing/templates.html



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ABC_Conference
  - title: facebook
    url: https://fb.me/ActivityBehaviorComputingConference
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/jekyll
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/abc-research


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
